name = "ls"
version = "0.1.0"

[[flags]]
name = "long"
type = "Bool"
help = "use a long listing format"
alias = ["l"]

[[flags]]
name = "dereference"
type = "Bool"
help = """
  when showing file information for a symlink, show information for file the
  link reference rather then for the link itself.
"""
alias = ["L"]

[[flags]]
name = "literal"
type = "Bool"
help = "print entry names without quoting"
alias = ["N"]

[[flags]]
name = "block_size"
value_name = "SIZE"
type = "I64"
default = "1024"
help = """
  with -l, scale sizes by SIZE when printing them; e.g., '--block-size=M'; see
  SIZE format below
"""
