name = "sample"
version = "0.1.0"

[[flags]]
name = "boolean_flag"
type = "boolean"
help = "boolean flag sample"
short = "b"

[[flags]]
name = "boolean_array"
type = "boolean"
multiple = true
help = "boolean array sample"

[[flags]]
name = "int64_flag"
short = "i"
type = "int64"
default = "1024"
help = "int64 flag sample"

[[flags]]
name = "float64_flag"
type = "float64"
default = "1024"
help = "int64 flag sample"
short = "f"

[[flags]]
name = "string_flag"
type = "string"
help = "string flag sample"
short = "s"
