name = "sample"
version = "0.1.0"

[[flags]]
name = "boolean_flag"
type = "boolean"
help = "boolean flag sample"

[[flags]]
name = "int64_flag"
type = "int64"
default = "1024"
help = "int64 flag sample"

[[flags]]
name = "float64_flag"
type = "float64"
default = "1024"
help = "int64 flag sample"

[[flags]]
name = "string_flag"
type = "string"
help = "string flag sample"
